apiVersion: v1
kind: Service
metadata: 
  name: python-app
spec:
  type: LoadBalancer
  selector: 
    app: python
  ports:
  - name:
    protocol: TCP      
    port: 8080
    targetPort: 5000
    nodePort: 30001

